name: BigQuery Trade Load

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'   # 02:00 UTC on the 1st of every month

jobs:
  load-trade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas google-cloud-bigquery

      - name: Run trade imports/exports load
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd projects/BigQuery
          echo "$GCP_SA_KEY" > sa.json
          export GOOGLE_APPLICATION_CREDENTIALS=sa.json
          python us_imports_exports.py
