name: refresh_rez_data
run-name: ${{ github.actor }} has refreshed the data

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit back to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython

      - name: Run rez_api.py
        working-directory: projects/park_reservations
        run: python rez_api.py

      - name: Commit rez_data.json to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rez_data.json
          git commit -m "Update rez_data.json [CI]" || echo "No changes to commit"
          git push
